### ISSUE TITLE
"fatal error: use of unimplemented initializer" when running

### ISSUE THREAD

**Issue by mctoon** [smileyborg/TableViewCellWithAutoLayoutiOS8#21]
I downloaded the zip, open in freshly updated xcode 6.2 and get this error:

/path-to/TableViewCellWithAutoLayoutiOS8-master/TableViewCellWithAutoLayout/TableViewController/TableViewController.swift: 10: 7: fatal error: use of unimplemented initializer 'init(nibName:bundle:)' for class 'TableViewCellWithAutoLayout.TableViewController'
(lldb)

**Comment by smileyborg** [comment]
Hi @mctoon,

Thanks for reporting this. Looks like it was caused by PR #19. Adding the following code back in to TableViewController.swift resolves the issue on Xcode 6.2:

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }

I need to test this on Xcode 6.3 beta, but based on PR #19 implementing that method as above actually causes issues in Swift 1.2.

**Comment by smileyborg** [comment]
@mctoon Please give it a try again. I just pushed some changes that make the code compatible with both Xcode 6.2 (Swift 1.1) and Xcode 6.3 beta 4 (Swift 1.2).

**Comment by mctoon** [comment]
Thank you, it works now.
